### ISSUE TITLE
Can't lsof of processes

### ISSUE THREAD

**Issue by pachulo** [maxiberta/htop-snap#1] opened 2018-05-15 13:57 UTC
Hi! First, thank for snaping this!

Second: I've seen that when I try to list the open files of a process (using 'l') I get this message:

`Could not execute 'lsof'. Please make sure it is available in your $PATH.`

I guess the solution would be as easy as adding `lsof` to the stage-packages, but I'm not sure.

Thanks again!

**Comment by maxiberta** [comment] 2018-05-15 19:44
Hey, thanks for the report! I've published a new revision to `candidate` which now includes the `lsof` binary; but still fails due to [snap security/sandboxing](https://forum.snapcraft.io/t/security-policy-and-sandboxing/554). This is being tracked in this [snapcraft forum topic](https://forum.snapcraft.io/t/htop-snap-unable-to-signal-aa-enforced-processes/5222/3).

A proper fix will probably need updated security policies in both `snapd` and the `htop` snap. In the meantime, please make sure to connect `htop` with all interfaces (`sudo snap connect htop:<interface>`, for all interfaces listed on `snap interfaces htop`); and if you feel like debugging apparmor profiles, [this topic](https://forum.snapcraft.io/t/security-policy-and-sandboxing/554) might help you hack a local fix.

**Comment by pachulo** [comment] 2018-05-27 00:34
Great! Now I see that the error is a lack of permissions and not that lsof cannot be executed: let's wait till they solve it then.

**Comment by pachulo** [comment] 2018-06-08 19:42
I've just refreshed core with the version available in the beta channel (2.33):

`snap refresh core --channel=beta`

And it now works!

**Comment by maxiberta** [comment] 2018-06-08 20:17
Thanks for the update. I'm unfortunately unable to reproduce, i.e. it's not working for me :-(. Maybe I'm missing something? Can you double check `htop` is actually `/snap/bin/htop`?

```
$ snap list core htop
Name  Version  Rev   Tracking  Developer  Notes
core  16-2.33  4830  beta      canonical  core
htop  2.2.0    381   stable    maxiberta  -

$ snap interfaces htop
Slot              Plug
:mount-observe    htop, ...
:process-control  htop, ...
:system-observe   htop, ...
```

**Comment by pachulo** [comment] 2018-06-08 21:10
Well, you're completely right, I was running the deb installed version... :(

I'm getting those denials:

`jun 08 23:16:37 xps audit[26331]: AVC apparmor="DENIED" operation="open" profile="snap.htop.htop" name="/proc/locks" pid=26331 comm="lsof" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
`

**Comment by maxiberta** [comment] 2018-12-17 23:04
This is now working as of:
```
snap    2.36.3
snapd   2.36.3
series  16
ubuntu  18.10
kernel  4.18.0-11-generic
```
```
Track    Arch     Channel    Version            Revision
latest   amd64    stable     2.2.0              1066
                  candidate  2.2.0              1066
                  beta       2.2.0-18-gb7b4200  1055
                  edge       3.0.0beta5         1059
         arm64    stable     2.2.0              1070
                  candidate  2.2.0              1070
                  beta       2.2.0-18-gb7b4200  1064
                  edge       3.0.0beta5         1062
         armhf    stable     2.2.0              1071
                  candidate  2.2.0              1071
                  beta       2.2.0-18-gb7b4200  1063
                  edge       3.0.0beta5         1061
         i386     stable     2.2.0              1069
                  candidate  2.2.0              1069
                  beta       2.2.0-18-gb7b4200  1054
                  edge       3.0.0beta5         1056
         powerpc  stable     2.2.0              1068
                  candidate  2.2.0              1068
                  beta       2.2.0-18-gb7b4200  1060
                  edge       3.0.0beta5         1037
         ppc64el  stable     2.2.0              1067
                  candidate  2.2.0              1067
                  beta       2.2.0-18-gb7b4200  1057
                  edge       3.0.0beta5         1058
         s390x    stable     2.2.0              1065
                  candidate  2.2.0              1065
                  beta       2.2.0-18-gb7b4200  1053
                  edge       3.0.0beta5         1052
```
Thank you for your patience!
Please feel free to re-open if this is not working as expected.

**Comment by pachulo** [comment] 2018-12-18 19:19
It seems to be failing still over here, but I'm using different distro version:
```
$ snap --version
snap    2.36.3
snapd   2.36.3
series  16
ubuntu  18.04
kernel  4.15.0-42-generic
```

**Comment by maxiberta** [comment] 2018-12-19 15:58
Right, it seems to be working on Ubuntu 18.10 only...

**Comment by maxiberta** [comment] 2018-12-19 16:19
Posted a question in the [snapcraft forum topic](https://forum.snapcraft.io/t/htop-snap-unable-to-signal-aa-enforced-processes/5222/16).

**Comment by maxiberta** [comment] 2019-11-28 18:57
This was fixed in `snapd` a long time ago.

**Closed as completed by maxiberta** 2019-11-28 18:57 UTC
