### ISSUE TITLE
htop 3.0.5 snap returns error message when starting.

### ISSUE THREAD

**Issue by ameinild** [maxiberta/htop-snap#12] opened 2021-02-05 17:06 UTC
The following error message is returned:
`Error: File /etc/sensors3.conf: Permission denied`

The application starts allright, but still drops the error message.
![htop_error](https://user-images.githubusercontent.com/434479/107065861-88790d00-67dd-11eb-8f1d-4be084ad77cd.jpg)

The file `/etc/sensors3.conf` is owned by root as expected.
Output of snap version:
```
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.04
kernel  5.4.0-64-generic
```

The apt/deb version of htop 3.0.5 works without issue.

**Comment by maxiberta** [comment] 2021-02-05 17:23
This is a duplicate of https://github.com/maxiberta/htop-snap/issues/10. The `hardware-observe` permission needs to be granted to the snap. It should work automatically for new installs, but might need manual connection if it's already installed.

**Closed as completed by maxiberta** 2021-02-05 17:23 UTC
