### ISSUE TITLE
WARNING: cannot create user data directory

### ISSUE THREAD

**Issue by lumarseg** [maxiberta/htop-snap#6] opened 2019-01-12 15:43 UTC
Hi! First, thank for snaping this!

I'm using Ubuntu Core in a Intel NUC board. Ubuntu Core 18 was installed on the internal eMMC storage (https://www.ubuntu.com/download/iot/intel-nuc).

Once Htop Snap is intalled, I run this command: 'htop' and there is a warning:

`2019/01/12 15:40:34.496324 cmd_run.go:835: WARNING: cannot create user data directory: cannot create "/home/iotcomm/snap/htop/1066": mkdir /home/iotcomm/snap: no space left on device
cannot create user data directory: /home/iotcomm/snap/htop/1066: No space left on device`

Best regards.

**Comment by maxiberta** [comment] 2019-01-14 03:07
Thanks for taking the time to report this. Does the command run at all after that warning is printed? 

I cannot test on the exact same hardware, but haven't been able to reproduce on kvm:

```
$ kvm -m 512M -redir tcp:3322::22 -hda ubuntu-core-18-amd64.img --snapshot
```

The `no space left on device` message looks like the disk is full. Please run `df -h` to check, and free up some space in `/home`, just in case.

**Comment by maxiberta** [comment] 2019-01-14 03:27
I've been able to reproduce on kvm by filling up the home directory (`/writable`, actually):

```
$ snap install htop
htop 2.2.0 from Maximiliano Bertacchini (maxiberta) installed

$ df -h /home
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       3.6G  356M  3.0G  11% /home

$ dd if=/dev/zero of=test bs=1M count=4096  # let's fill up the free space
dd: error writing 'test': No space left on device
3033+0 records in
3032+0 records out
3180122112 bytes (3.2 GB, 3.0 GiB) copied, 29.5851 s, 107 MB/s

$ htop  # command fails to start
2019/01/14 03:14:45.263217 cmd_run.go:835: WARNING: cannot create user data directory: cannot create "/home/maxiberta-prd/snap/htop/1066": mkdir /home/maxiberta-prd/snap: no space left on device
cannot create user data directory: /home/maxiberta-prd/snap/htop/1066: No space left on device

$ rm test  # let's free up some space

$ htop  # now it works
locales-launch: Data of en_US locale not found, generating, please wait...
```
So I definitely believe the issue is a full writable partition. I'd suggest:
1. Try to free up some space.
2. Try running the command directly as `/snap/htop/current/bin/htop` (which won't try to compile the locale definition files).

That said, I see a couple of possible improvements in this snap:
* ~~The [locales-launch](https://github.com/Lin-Buo-Ren/locales-launch-part) wrapper could be a bit smarter and not crash.~~ (it's snapd, not `locales-launch`)
* The snap could be based on `core18`, which is built into Ubuntu Core 18 images, to prevent downloading the `core` snap.

**Comment by maxiberta** [comment] 2019-01-15 19:33
Looks like a local issue not caused by the snap. Feel free to reopen if that's not the case. Closing.

**Closed as completed by maxiberta** 2019-01-15 19:33 UTC

**Comment by lumarseg** [comment] 2019-01-22 19:29
Hi, it was a mistake from me. It's necesary to run htop as sudo:

`sudo htop`

Best regards,

Luis
